// Auto-generated city data — single source of truth for service-area pages.
// Edit cities here to update all 20 service area pages at once.

export type CityFAQ = { q: string; a: string }

export type CityData = {
  slug: string
  display: string
  county: string
  lat: number
  lng: number
  coastal: boolean
  tier: 'major' | 'mid'
  metaDescription: string
  heroSubhead: string
  introParagraphs: string[]
  heroPhotoId: string
  faqs: CityFAQ[]
}

export const CITIES: Record<string, CityData> = {
  'tampa-fl': {
    slug: 'tampa-fl',
    display: "Tampa",
    county: 'Hillsborough County',
    lat: 27.9506,
    lng: -82.4572,
    coastal: false,
    tier: 'major',
    metaDescription: `North East Heating And Cooling provides expert HVAC repair, AC installation, heating services, and air duct repair throughout Tampa, FL. Call (813) 291-6146 for same-day service.`,
    heroSubhead: `Professional heating, air conditioning, and ventilation services for Tampa homeowners and businesses. Licensed technicians, transparent pricing, and same-day availability.`,
    heroPhotoId: '7577378',
    introParagraphs: [
      `Tampa is Florida's third-largest city and one of the fastest-growing metros in the country, home to over 400,000 residents spread across vibrant neighborhoods like South Tampa, Westchase, New Tampa, Seminole Heights, and Ybor City. With a subtropical climate that delivers sweltering summers, high humidity, and mild winters, Tampa residents depend on their HVAC systems year-round to stay comfortable and healthy. When temperatures regularly push past 90°F from June through September and heat indices climb even higher, a failing air conditioner isn't just uncomfortable — it can be dangerous.`,
      `North East Heating And Cooling has served Tampa homeowners and commercial clients for years, building a reputation on fast response times, honest diagnostics, and workmanship that stands up to Florida's demanding climate. Our licensed and insured technicians are familiar with every neighborhood in Tampa, meaning shorter drive times and faster service for you. Whether you're in a historic Seminole Heights bungalow, a newer construction home in New Tampa, or a commercial storefront downtown, we have the tools and expertise to keep your system running at peak efficiency.`,
    ],
    faqs: [
      { q: `How quickly can you get to Tampa for an AC repair?`, a: `For most Tampa service calls we offer same-day or next-day appointments. For emergency breakdowns we dispatch the nearest technician — typically within 1–2 hours depending on traffic and current service volume. Our service vans are stocked with the most common repair parts so the majority of repairs are resolved on the first visit.` },
      { q: `Do you charge a service fee for AC repair calls in Tampa?`, a: `We charge a standard diagnostic fee that covers the technician's travel and full system inspection. The diagnostic fee is waived if you proceed with the repair, and members of our maintenance plan don't pay it at all. Every repair quote is provided in writing before any work begins — no surprise charges.` },
      { q: `What is the average cost of AC repair in Tampa?`, a: `Most Tampa AC repairs fall in the $150–$600 range. Common fixes like capacitor replacement run $150–$300, while bigger jobs like compressor replacement can reach $1,000–$1,800. We always quote in writing upfront, and on aging systems we'll quote both the repair cost and a replacement option side-by-side so you can choose with full information.` },
      { q: `What areas of Tampa do you serve?`, a: `We serve all of Tampa and the surrounding Hillsborough County area. Our techs cover every neighborhood in the city, from established residential areas to newer developments. We typically arrive within our standard service window regardless of where you are in Tampa.` },
      { q: `Do you service mobile homes in Tampa?`, a: `Yes — we service all types of residential properties in Tampa, including mobile homes, manufactured homes, and modular homes. Mobile home HVAC systems often have unique configurations (like under-floor ductwork or roof-mounted package units) that require specific expertise. Our technicians are trained on these systems.` },
      { q: `Do you handle both residential and commercial work in Tampa?`, a: `Yes. We service residential homes, small commercial buildings, restaurants, retail locations, and offices throughout Tampa. Commercial clients typically receive priority dispatch since downtime affects business operations. We work on rooftop units, split systems, and packaged units of all sizes.` },
    ],
  },
  'brandon-fl': {
    slug: 'brandon-fl',
    display: "Brandon",
    county: 'Hillsborough County',
    lat: 27.9378,
    lng: -82.2859,
    coastal: false,
    tier: 'major',
    metaDescription: `Trusted HVAC repair, AC installation, heating services, and air duct repair in Brandon, FL. North East Heating And Cooling — call (813) 291-6146 for same-day service.`,
    heroSubhead: `Reliable heating, air conditioning, and ventilation services for Brandon homeowners and businesses. Fast response, honest pricing, and technicians who know Hillsborough County.`,
    heroPhotoId: '8961065',
    introParagraphs: [
      `Brandon is one of Hillsborough County's most populous unincorporated communities, home to approximately 115,000 residents and one of the fastest-growing suburban areas in the Tampa Bay region. Situated just east of Tampa along the Interstate 60 and Brandon Boulevard corridors, Brandon features a diverse mix of established neighborhoods, newer subdivisions, and a robust commercial corridor packed with retail, restaurants, and medical facilities.`,
      `Brandon's inland location means it experiences the full force of Florida's summer heat without the slight coastal moderating effect enjoyed by beachside communities. Summer temperatures regularly reach the mid-to-upper 90s, and the combination of heat and humidity makes a functioning air conditioner absolutely essential for comfortable living. Many of Brandon's homes — particularly those in established neighborhoods like Bloomingdale and Lakeview Village — feature ductwork and HVAC systems installed in the 1980s and 1990s that are approaching or past their useful service life.`,
    ],
    faqs: [
      { q: `What is the average cost of AC repair in Brandon?`, a: `Most Brandon AC repairs fall in the $150–$600 range. Common fixes like capacitor replacement run $150–$300, while bigger jobs like compressor replacement can reach $1,000–$1,800. We always quote in writing upfront, and on aging systems we'll quote both the repair cost and a replacement option side-by-side so you can choose with full information.` },
      { q: `What areas of Brandon do you serve?`, a: `We serve all of Brandon and the surrounding Hillsborough County area. Our techs cover every neighborhood in the city, from established residential areas to newer developments. We typically arrive within our standard service window regardless of where you are in Brandon.` },
      { q: `Do you service mobile homes in Brandon?`, a: `Yes — we service all types of residential properties in Brandon, including mobile homes, manufactured homes, and modular homes. Mobile home HVAC systems often have unique configurations (like under-floor ductwork or roof-mounted package units) that require specific expertise. Our technicians are trained on these systems.` },
      { q: `Do you handle both residential and commercial work in Brandon?`, a: `Yes. We service residential homes, small commercial buildings, restaurants, retail locations, and offices throughout Brandon. Commercial clients typically receive priority dispatch since downtime affects business operations. We work on rooftop units, split systems, and packaged units of all sizes.` },
      { q: `What HVAC brands do you service in Brandon?`, a: `We service every major HVAC brand: Carrier, Trane, Lennox, Rheem, Goodman, York, American Standard, Bryant, Daikin, Mitsubishi, and others. Our service vans carry parts for the most common brands and we can source specialty parts within 24–48 hours when needed. We work on systems from any installer, including ones we didn't install.` },
      { q: `Do you install heat pumps in Brandon?`, a: `Yes. Heat pumps are an excellent choice for Brandon given Florida's mild winters — they handle both cooling and heating efficiently year-round. We install variable-speed inverter heat pumps, traditional split heat pumps, and packaged units. Many qualifying systems are eligible for federal tax credits up to $2,000.` },
    ],
  },
  'riverview-fl': {
    slug: 'riverview-fl',
    display: "Riverview",
    county: 'Hillsborough County',
    lat: 27.8661,
    lng: -82.3265,
    coastal: false,
    tier: 'major',
    metaDescription: `Expert HVAC repair, AC installation, heating services, and air duct repair in Riverview, FL. North East Heating And Cooling — call (813) 291-6146 for fast, reliable service.`,
    heroSubhead: `Professional heating, cooling, and air quality solutions for Riverview's rapidly growing residential and commercial communities. Same-day service available throughout Hillsborough County.`,
    heroPhotoId: '4078319',
    introParagraphs: [
      `Riverview is one of the fastest-growing communities in all of Florida, with a population that has exploded from around 71,000 in 2010 to well over 120,000 residents today. Located in southeastern Hillsborough County along the Alafia River, Riverview's rapid development has brought dozens of new residential communities, including communities like Summerfield, Panther Trace, South Fork, Triple Creek, and Boyette Springs — each filled with newer homes and the growing families that call Riverview home.`,
      `While newer construction homes often feature modern, efficient HVAC systems, the rapid pace of Riverview's development means many homes were built quickly and may have ductwork, equipment, or installation practices that fall short of optimal. Homeowners in newer Riverview subdivisions sometimes discover that their relatively new systems are not performing as expected due to duct leakage, improper airflow balancing, or equipment that was sized to the minimum acceptable standard to reduce builder costs.`,
    ],
    faqs: [
      { q: `Do you service mobile homes in Riverview?`, a: `Yes — we service all types of residential properties in Riverview, including mobile homes, manufactured homes, and modular homes. Mobile home HVAC systems often have unique configurations (like under-floor ductwork or roof-mounted package units) that require specific expertise. Our technicians are trained on these systems.` },
      { q: `Do you handle both residential and commercial work in Riverview?`, a: `Yes. We service residential homes, small commercial buildings, restaurants, retail locations, and offices throughout Riverview. Commercial clients typically receive priority dispatch since downtime affects business operations. We work on rooftop units, split systems, and packaged units of all sizes.` },
      { q: `What HVAC brands do you service in Riverview?`, a: `We service every major HVAC brand: Carrier, Trane, Lennox, Rheem, Goodman, York, American Standard, Bryant, Daikin, Mitsubishi, and others. Our service vans carry parts for the most common brands and we can source specialty parts within 24–48 hours when needed. We work on systems from any installer, including ones we didn't install.` },
      { q: `Do you install heat pumps in Riverview?`, a: `Yes. Heat pumps are an excellent choice for Riverview given Florida's mild winters — they handle both cooling and heating efficiently year-round. We install variable-speed inverter heat pumps, traditional split heat pumps, and packaged units. Many qualifying systems are eligible for federal tax credits up to $2,000.` },
      { q: `Do you install ductless mini-splits in Riverview?`, a: `Yes. We install single-zone and multi-zone ductless mini-splits throughout Riverview — perfect for additions, garages, sunrooms, or older homes without ductwork. We work with premium brands including Mitsubishi, Daikin, LG, and Fujitsu, and provide free in-home assessments to determine the right system size.` },
      { q: `How often should I have my AC maintained in Riverview?`, a: `Twice a year — once in spring (March–April) before peak cooling, and once in fall (October–November). Tampa Bay's climate puts significantly more wear on AC systems than northern climates, so twice-yearly service is the standard for keeping equipment running efficiently and avoiding mid-summer breakdowns. Our maintenance plans for Riverview start at $19/mo.` },
    ],
  },
  'wesley-chapel-fl': {
    slug: 'wesley-chapel-fl',
    display: "Wesley Chapel",
    county: 'Pasco County',
    lat: 28.2397,
    lng: -82.3279,
    coastal: false,
    tier: 'major',
    metaDescription: `Professional HVAC repair, AC installation & maintenance in Wesley Chapel, FL. Licensed technicians serving this rapidly growing suburb with new construction expertise. Call (813) 291-6146.`,
    heroSubhead: `Professional heating and cooling services for Wesley Chapel's rapidly expanding residential communities and new construction developments.`,
    heroPhotoId: '3855962',
    introParagraphs: [
      `Wesley Chapel has become one of the fastest-growing communities in the entire state of Florida, with thousands of new homes, master-planned communities, and commercial developments coming online each year. Located in Pasco County just north of Tampa, Wesley Chapel attracts families, young professionals, and retirees drawn to its excellent schools, modern amenities, and high quality of life. With this growth comes increased demand for professional, reliable HVAC services — because in Florida, a functioning air conditioning system is not optional.`,
      `North East Heating And Cooling is proud to serve Wesley Chapel with expert HVAC repair, installation, and maintenance services. Whether your home was just built or is a few years old, our licensed technicians provide the quality service your family deserves. We work with all major HVAC brands and stay current with the latest equipment and installation best practices to ensure your home stays comfortable year-round.`,
    ],
    faqs: [
      { q: `What HVAC brands do you service in Wesley Chapel?`, a: `We service every major HVAC brand: Carrier, Trane, Lennox, Rheem, Goodman, York, American Standard, Bryant, Daikin, Mitsubishi, and others. Our service vans carry parts for the most common brands and we can source specialty parts within 24–48 hours when needed. We work on systems from any installer, including ones we didn't install.` },
      { q: `Do you install heat pumps in Wesley Chapel?`, a: `Yes. Heat pumps are an excellent choice for Wesley Chapel given Florida's mild winters — they handle both cooling and heating efficiently year-round. We install variable-speed inverter heat pumps, traditional split heat pumps, and packaged units. Many qualifying systems are eligible for federal tax credits up to $2,000.` },
      { q: `Do you install ductless mini-splits in Wesley Chapel?`, a: `Yes. We install single-zone and multi-zone ductless mini-splits throughout Wesley Chapel — perfect for additions, garages, sunrooms, or older homes without ductwork. We work with premium brands including Mitsubishi, Daikin, LG, and Fujitsu, and provide free in-home assessments to determine the right system size.` },
      { q: `How often should I have my AC maintained in Wesley Chapel?`, a: `Twice a year — once in spring (March–April) before peak cooling, and once in fall (October–November). Tampa Bay's climate puts significantly more wear on AC systems than northern climates, so twice-yearly service is the standard for keeping equipment running efficiently and avoiding mid-summer breakdowns. Our maintenance plans for Wesley Chapel start at $19/mo.` },
      { q: `Do you offer maintenance plans in Wesley Chapel?`, a: `Yes. Our maintenance plans for Wesley Chapel customers include twice-yearly tune-ups, a 20-point inspection at every visit, priority scheduling during peak seasons, a 15% discount on any repairs, and no diagnostic fees. Plans start at $19/mo with no long-term contract — cancel any time.` },
      { q: `Do you offer 24/7 emergency HVAC service in Wesley Chapel?`, a: `Yes. We provide 24/7 emergency AC repair throughout Wesley Chapel — Florida's heat makes a broken AC a health concern within hours, especially for elderly residents, young children, and pets. When you call our emergency line, a live technician answers and we dispatch the nearest available crew.` },
    ],
  },
  'clearwater-fl': {
    slug: 'clearwater-fl',
    display: "Clearwater",
    county: 'Pinellas County',
    lat: 27.9658,
    lng: -82.8001,
    coastal: true,
    tier: 'major',
    metaDescription: `Professional HVAC repair, AC installation, heating services, and air duct repair in Clearwater, FL. North East Heating And Cooling — call (813) 291-6146 for fast, reliable service.`,
    heroSubhead: `Expert heating, air conditioning, and ventilation services for Clearwater residents and businesses. Coastal climate specialists available for same-day and emergency service.`,
    heroPhotoId: '7983215',
    introParagraphs: [
      `Clearwater is one of the crown jewels of Florida's Gulf Coast, home to world-famous Clearwater Beach, a thriving downtown entertainment district, and residential neighborhoods that attract both year-round residents and seasonal snowbirds. With approximately 117,000 full-time residents — and tens of thousands more who visit or part-time in the area — Clearwater has a diverse housing stock ranging from mid-century beachside cottages to luxury waterfront condominiums and sprawling suburban developments east of US-19.`,
      `Clearwater's proximity to the Gulf of Mexico creates a climate that is both beautiful and demanding on HVAC equipment. Salt-laden sea breezes accelerate corrosion on condenser coils and electrical components, while the city's subtropical heat and humidity keep air conditioners running for the better part of the year. North East Heating And Cooling's technicians are well-versed in the specific challenges of servicing HVAC systems in coastal Pinellas County environments, and we can recommend corrosion-resistant components and protective coatings that significantly extend equipment life near the coast.`,
    ],
    faqs: [
      { q: `Do you install ductless mini-splits in Clearwater?`, a: `Yes. We install single-zone and multi-zone ductless mini-splits throughout Clearwater — perfect for additions, garages, sunrooms, or older homes without ductwork. We work with premium brands including Mitsubishi, Daikin, LG, and Fujitsu, and provide free in-home assessments to determine the right system size.` },
      { q: `How often should I have my AC maintained in Clearwater?`, a: `Twice a year — once in spring (March–April) before peak cooling, and once in fall (October–November). Tampa Bay's climate puts significantly more wear on AC systems than northern climates, so twice-yearly service is the standard for keeping equipment running efficiently and avoiding mid-summer breakdowns. Our maintenance plans for Clearwater start at $19/mo.` },
      { q: `Do you offer maintenance plans in Clearwater?`, a: `Yes. Our maintenance plans for Clearwater customers include twice-yearly tune-ups, a 20-point inspection at every visit, priority scheduling during peak seasons, a 15% discount on any repairs, and no diagnostic fees. Plans start at $19/mo with no long-term contract — cancel any time.` },
      { q: `Does the salt air in Clearwater affect my AC system?`, a: `Yes — homes in Clearwater near the water are exposed to salt-laden humidity that accelerates corrosion of aluminum coil fins, copper refrigerant lines, and outdoor electrical contacts. Coastal homes typically see AC lifespan reduced by 2–4 years compared to inland homes. We recommend coastal-rated equipment with corrosion-resistant coatings for waterfront installations, plus more aggressive maintenance schedules.` },
      { q: `How do you protect HVAC equipment from Clearwater's coastal environment?`, a: `For coastal Clearwater installations we recommend equipment with corrosion-resistant coatings on the outdoor condenser, more frequent coil cleaning to remove salt deposits, and protective covers for unused months. Ground-level installations should be elevated to protect against tropical storm surge. We help homeowners choose equipment specifically rated for coastal climates.` },
      { q: `Do you offer 24/7 emergency HVAC service in Clearwater?`, a: `Yes. We provide 24/7 emergency AC repair throughout Clearwater — Florida's heat makes a broken AC a health concern within hours, especially for elderly residents, young children, and pets. When you call our emergency line, a live technician answers and we dispatch the nearest available crew.` },
    ],
  },
  'st-petersburg-fl': {
    slug: 'st-petersburg-fl',
    display: "St. Petersburg",
    county: 'Pinellas County',
    lat: 27.7676,
    lng: -82.6403,
    coastal: true,
    tier: 'major',
    metaDescription: `Expert HVAC repair, AC installation, heating services, and air duct repair throughout St. Petersburg, FL. North East Heating And Cooling — call (813) 291-6146 for same-day service.`,
    heroSubhead: `Dependable heating, cooling, and air quality services for St. Pete homes and businesses. Fast response times, honest pricing, and licensed technicians ready to serve you today.`,
    heroPhotoId: '3875141',
    introParagraphs: [
      `St. Petersburg — affectionately known as "St. Pete" — is one of Florida's most beloved cities, boasting world-class beaches, a thriving arts scene, and a walkable downtown filled with restaurants, galleries, and boutiques. With a population approaching 260,000, St. Pete is the fourth-largest city in Florida and a community where quality of life is taken seriously. That includes staying cool and comfortable in a city that holds the Guinness World Record for consecutive days of sunshine.`,
      `St. Petersburg's peninsular location means it is surrounded by water on three sides — Tampa Bay to the east and the Gulf of Mexico to the west. This geography moderates temperatures slightly but also contributes to extremely high humidity levels, especially during the summer months. Salt air from the coast accelerates corrosion of HVAC components, meaning systems in St. Pete often require more frequent maintenance and inspection than those in inland areas. North East Heating And Cooling technicians understand these coastal HVAC challenges and can recommend corrosion-resistant equipment and coatings to extend system lifespan.`,
    ],
    faqs: [
      { q: `Do you offer maintenance plans in St. Petersburg?`, a: `Yes. Our maintenance plans for St. Petersburg customers include twice-yearly tune-ups, a 20-point inspection at every visit, priority scheduling during peak seasons, a 15% discount on any repairs, and no diagnostic fees. Plans start at $19/mo with no long-term contract — cancel any time.` },
      { q: `Does the salt air in St. Petersburg affect my AC system?`, a: `Yes — homes in St. Petersburg near the water are exposed to salt-laden humidity that accelerates corrosion of aluminum coil fins, copper refrigerant lines, and outdoor electrical contacts. Coastal homes typically see AC lifespan reduced by 2–4 years compared to inland homes. We recommend coastal-rated equipment with corrosion-resistant coatings for waterfront installations, plus more aggressive maintenance schedules.` },
      { q: `How do you protect HVAC equipment from St. Petersburg's coastal environment?`, a: `For coastal St. Petersburg installations we recommend equipment with corrosion-resistant coatings on the outdoor condenser, more frequent coil cleaning to remove salt deposits, and protective covers for unused months. Ground-level installations should be elevated to protect against tropical storm surge. We help homeowners choose equipment specifically rated for coastal climates.` },
      { q: `Do you offer 24/7 emergency HVAC service in St. Petersburg?`, a: `Yes. We provide 24/7 emergency AC repair throughout St. Petersburg — Florida's heat makes a broken AC a health concern within hours, especially for elderly residents, young children, and pets. When you call our emergency line, a live technician answers and we dispatch the nearest available crew.` },
      { q: `How quickly can you get to St. Petersburg for an AC repair?`, a: `For most St. Petersburg service calls we offer same-day or next-day appointments. For emergency breakdowns we dispatch the nearest technician — typically within 1–2 hours depending on traffic and current service volume. Our service vans are stocked with the most common repair parts so the majority of repairs are resolved on the first visit.` },
      { q: `Do you charge a service fee for AC repair calls in St. Petersburg?`, a: `We charge a standard diagnostic fee that covers the technician's travel and full system inspection. The diagnostic fee is waived if you proceed with the repair, and members of our maintenance plan don't pay it at all. Every repair quote is provided in writing before any work begins — no surprise charges.` },
    ],
  },
  'largo-fl': {
    slug: 'largo-fl',
    display: "Largo",
    county: 'Pinellas County',
    lat: 27.9095,
    lng: -82.7878,
    coastal: false,
    tier: 'mid',
    metaDescription: `Professional HVAC repair, AC installation & maintenance in Largo, FL. Licensed technicians serving Pinellas County's second largest city. Call (813) 291-6146 for fast service.`,
    heroSubhead: `Comprehensive heating and cooling services for Largo residents and businesses — Pinellas County's second largest city.`,
    heroPhotoId: '5825527',
    introParagraphs: [
      `Largo is the second largest city in Pinellas County and one of the most vibrant communities in the Tampa Bay area. With a diverse mix of residential neighborhoods, thriving businesses, and proximity to Florida's Gulf Coast, Largo offers its residents a high quality of life — and year-round warm weather that demands dependable air conditioning. Whether you live in a single-family home, a condo, or manage a commercial property, keeping your HVAC system in peak condition is essential.`,
      `North East Heating And Cooling provides full-service HVAC solutions for Largo homes and businesses. Our licensed technicians are familiar with the wide range of property types and HVAC systems found throughout the city. From prompt emergency repairs to carefully planned new installations, we deliver reliable, professional service backed by transparent pricing.`,
    ],
    faqs: [
      { q: `How quickly can you get to Largo for an AC repair?`, a: `For most Largo service calls we offer same-day or next-day appointments. For emergency breakdowns we dispatch the nearest technician — typically within 1–2 hours depending on traffic and current service volume. Our service vans are stocked with the most common repair parts so the majority of repairs are resolved on the first visit.` },
      { q: `Do you charge a service fee for AC repair calls in Largo?`, a: `We charge a standard diagnostic fee that covers the technician's travel and full system inspection. The diagnostic fee is waived if you proceed with the repair, and members of our maintenance plan don't pay it at all. Every repair quote is provided in writing before any work begins — no surprise charges.` },
      { q: `What is the average cost of AC repair in Largo?`, a: `Most Largo AC repairs fall in the $150–$600 range. Common fixes like capacitor replacement run $150–$300, while bigger jobs like compressor replacement can reach $1,000–$1,800. We always quote in writing upfront, and on aging systems we'll quote both the repair cost and a replacement option side-by-side so you can choose with full information.` },
      { q: `What areas of Largo do you serve?`, a: `We serve all of Largo and the surrounding Pinellas County area. Our techs cover every neighborhood in the city, from established residential areas to newer developments. We typically arrive within our standard service window regardless of where you are in Largo.` },
      { q: `Do you service mobile homes in Largo?`, a: `Yes — we service all types of residential properties in Largo, including mobile homes, manufactured homes, and modular homes. Mobile home HVAC systems often have unique configurations (like under-floor ductwork or roof-mounted package units) that require specific expertise. Our technicians are trained on these systems.` },
      { q: `Do you handle both residential and commercial work in Largo?`, a: `Yes. We service residential homes, small commercial buildings, restaurants, retail locations, and offices throughout Largo. Commercial clients typically receive priority dispatch since downtime affects business operations. We work on rooftop units, split systems, and packaged units of all sizes.` },
    ],
  },
  'palm-harbor-fl': {
    slug: 'palm-harbor-fl',
    display: "Palm Harbor",
    county: 'Pinellas County',
    lat: 28.078,
    lng: -82.7637,
    coastal: true,
    tier: 'mid',
    metaDescription: `Professional HVAC repair, AC installation & maintenance in Palm Harbor, FL. Licensed technicians serving this coastal community in Pinellas County. Call (813) 291-6146 for fast service.`,
    heroSubhead: `Expert HVAC repair, installation, and maintenance for Palm Harbor's coastal community — where humidity and heat demand the best in cooling technology.`,
    heroPhotoId: '7534294',
    introParagraphs: [
      `Palm Harbor is one of Pinellas County's most desirable coastal communities, attracting residents who appreciate its beautiful neighborhoods, top-rated schools, and proximity to the Gulf of Mexico. Living near the coast offers many advantages, but it also comes with a challenging climate — high humidity, salt air, and intense summer heat that puts HVAC systems under significant stress year-round. In Palm Harbor, a well-maintained, properly sized air conditioning system is essential for comfortable living.`,
      `North East Heating And Cooling provides comprehensive HVAC services throughout Palm Harbor. Our licensed technicians understand the unique demands that coastal Florida's climate places on HVAC equipment and bring the expertise needed to keep your system running efficiently through every season. From emergency repairs to complete system replacements, we're here to serve Palm Harbor homeowners and businesses.`,
    ],
    faqs: [
      { q: `How quickly can you get to Palm Harbor for an AC repair?`, a: `For most Palm Harbor service calls we offer same-day or next-day appointments. For emergency breakdowns we dispatch the nearest technician — typically within 1–2 hours depending on traffic and current service volume. Our service vans are stocked with the most common repair parts so the majority of repairs are resolved on the first visit.` },
      { q: `Do you charge a service fee for AC repair calls in Palm Harbor?`, a: `We charge a standard diagnostic fee that covers the technician's travel and full system inspection. The diagnostic fee is waived if you proceed with the repair, and members of our maintenance plan don't pay it at all. Every repair quote is provided in writing before any work begins — no surprise charges.` },
      { q: `What is the average cost of AC repair in Palm Harbor?`, a: `Most Palm Harbor AC repairs fall in the $150–$600 range. Common fixes like capacitor replacement run $150–$300, while bigger jobs like compressor replacement can reach $1,000–$1,800. We always quote in writing upfront, and on aging systems we'll quote both the repair cost and a replacement option side-by-side so you can choose with full information.` },
      { q: `What areas of Palm Harbor do you serve?`, a: `We serve all of Palm Harbor and the surrounding Pinellas County area. Our techs cover every neighborhood in the city, from established residential areas to newer developments. We typically arrive within our standard service window regardless of where you are in Palm Harbor.` },
      { q: `Do you service mobile homes in Palm Harbor?`, a: `Yes — we service all types of residential properties in Palm Harbor, including mobile homes, manufactured homes, and modular homes. Mobile home HVAC systems often have unique configurations (like under-floor ductwork or roof-mounted package units) that require specific expertise. Our technicians are trained on these systems.` },
      { q: `Do you handle both residential and commercial work in Palm Harbor?`, a: `Yes. We service residential homes, small commercial buildings, restaurants, retail locations, and offices throughout Palm Harbor. Commercial clients typically receive priority dispatch since downtime affects business operations. We work on rooftop units, split systems, and packaged units of all sizes.` },
    ],
  },
  'pinellas-park-fl': {
    slug: 'pinellas-park-fl',
    display: "Pinellas Park",
    county: 'Pinellas County',
    lat: 27.8428,
    lng: -82.6995,
    coastal: false,
    tier: 'mid',
    metaDescription: `Professional HVAC repair, AC installation & maintenance in Pinellas Park, FL. Licensed technicians serving this diverse Pinellas County community. Call (813) 291-6146 for fast service.`,
    heroSubhead: `Dependable heating and cooling solutions for Pinellas Park's diverse residential neighborhoods and active commercial community.`,
    heroPhotoId: '7577378',
    introParagraphs: [
      `Pinellas Park is a vibrant, diverse community located in the heart of Pinellas County, surrounded by St. Petersburg, Clearwater, and Largo. With a mix of long-established neighborhoods, mobile home communities, newer subdivisions, and a strong commercial and light industrial sector, Pinellas Park represents the full breadth of Florida living. And in Florida's hot, humid climate, reliable air conditioning is a necessity for every type of property in the city.`,
      `North East Heating And Cooling serves Pinellas Park homeowners and businesses with professional HVAC repair, installation, and maintenance services. Our experienced technicians understand the variety of HVAC systems and property types found throughout the city and provide service tailored to your specific needs — all at transparent, competitive pricing.`,
    ],
    faqs: [
      { q: `Do you service mobile homes in Pinellas Park?`, a: `Yes — we service all types of residential properties in Pinellas Park, including mobile homes, manufactured homes, and modular homes. Mobile home HVAC systems often have unique configurations (like under-floor ductwork or roof-mounted package units) that require specific expertise. Our technicians are trained on these systems.` },
      { q: `Do you handle both residential and commercial work in Pinellas Park?`, a: `Yes. We service residential homes, small commercial buildings, restaurants, retail locations, and offices throughout Pinellas Park. Commercial clients typically receive priority dispatch since downtime affects business operations. We work on rooftop units, split systems, and packaged units of all sizes.` },
      { q: `What HVAC brands do you service in Pinellas Park?`, a: `We service every major HVAC brand: Carrier, Trane, Lennox, Rheem, Goodman, York, American Standard, Bryant, Daikin, Mitsubishi, and others. Our service vans carry parts for the most common brands and we can source specialty parts within 24–48 hours when needed. We work on systems from any installer, including ones we didn't install.` },
      { q: `Do you install heat pumps in Pinellas Park?`, a: `Yes. Heat pumps are an excellent choice for Pinellas Park given Florida's mild winters — they handle both cooling and heating efficiently year-round. We install variable-speed inverter heat pumps, traditional split heat pumps, and packaged units. Many qualifying systems are eligible for federal tax credits up to $2,000.` },
      { q: `Do you install ductless mini-splits in Pinellas Park?`, a: `Yes. We install single-zone and multi-zone ductless mini-splits throughout Pinellas Park — perfect for additions, garages, sunrooms, or older homes without ductwork. We work with premium brands including Mitsubishi, Daikin, LG, and Fujitsu, and provide free in-home assessments to determine the right system size.` },
      { q: `How often should I have my AC maintained in Pinellas Park?`, a: `Twice a year — once in spring (March–April) before peak cooling, and once in fall (October–November). Tampa Bay's climate puts significantly more wear on AC systems than northern climates, so twice-yearly service is the standard for keeping equipment running efficiently and avoiding mid-summer breakdowns. Our maintenance plans for Pinellas Park start at $19/mo.` },
    ],
  },
  'carrollwood-fl': {
    slug: 'carrollwood-fl',
    display: "Carrollwood",
    county: 'Hillsborough County',
    lat: 28.05,
    lng: -82.494,
    coastal: false,
    tier: 'mid',
    metaDescription: `Professional HVAC repair, AC installation & maintenance in Carrollwood, FL. Licensed technicians serving established Tampa suburbs. Call (813) 291-6146 for fast service.`,
    heroSubhead: `Reliable heating and cooling solutions for Carrollwood's established residential neighborhoods and growing community.`,
    heroPhotoId: '8961065',
    introParagraphs: [
      `Carrollwood is one of Tampa's most established and sought-after suburban communities, known for its mature tree-lined streets, well-kept neighborhoods, and convenient access to everything the greater Tampa area has to offer. Residents here take pride in their homes, and that includes keeping their HVAC systems running efficiently year-round. With Florida's intense summer heat and humidity, a properly functioning air conditioning system is essential to comfortable living in Carrollwood.`,
      `North East Heating And Cooling has served Carrollwood homeowners and businesses for years, delivering professional HVAC repair, installation, and maintenance services with the attention to detail that this community deserves. Whether your home was built in the 1970s or the 2000s, our licensed technicians have the expertise to service all makes and models of heating and cooling equipment.`,
    ],
    faqs: [
      { q: `What HVAC brands do you service in Carrollwood?`, a: `We service every major HVAC brand: Carrier, Trane, Lennox, Rheem, Goodman, York, American Standard, Bryant, Daikin, Mitsubishi, and others. Our service vans carry parts for the most common brands and we can source specialty parts within 24–48 hours when needed. We work on systems from any installer, including ones we didn't install.` },
      { q: `Do you install heat pumps in Carrollwood?`, a: `Yes. Heat pumps are an excellent choice for Carrollwood given Florida's mild winters — they handle both cooling and heating efficiently year-round. We install variable-speed inverter heat pumps, traditional split heat pumps, and packaged units. Many qualifying systems are eligible for federal tax credits up to $2,000.` },
      { q: `Do you install ductless mini-splits in Carrollwood?`, a: `Yes. We install single-zone and multi-zone ductless mini-splits throughout Carrollwood — perfect for additions, garages, sunrooms, or older homes without ductwork. We work with premium brands including Mitsubishi, Daikin, LG, and Fujitsu, and provide free in-home assessments to determine the right system size.` },
      { q: `How often should I have my AC maintained in Carrollwood?`, a: `Twice a year — once in spring (March–April) before peak cooling, and once in fall (October–November). Tampa Bay's climate puts significantly more wear on AC systems than northern climates, so twice-yearly service is the standard for keeping equipment running efficiently and avoiding mid-summer breakdowns. Our maintenance plans for Carrollwood start at $19/mo.` },
      { q: `Do you offer maintenance plans in Carrollwood?`, a: `Yes. Our maintenance plans for Carrollwood customers include twice-yearly tune-ups, a 20-point inspection at every visit, priority scheduling during peak seasons, a 15% discount on any repairs, and no diagnostic fees. Plans start at $19/mo with no long-term contract — cancel any time.` },
      { q: `Do you offer 24/7 emergency HVAC service in Carrollwood?`, a: `Yes. We provide 24/7 emergency AC repair throughout Carrollwood — Florida's heat makes a broken AC a health concern within hours, especially for elderly residents, young children, and pets. When you call our emergency line, a live technician answers and we dispatch the nearest available crew.` },
    ],
  },
  'lutz-fl': {
    slug: 'lutz-fl',
    display: "Lutz",
    county: 'Hillsborough County',
    lat: 28.155,
    lng: -82.4612,
    coastal: false,
    tier: 'mid',
    metaDescription: `Professional HVAC repair, AC installation & maintenance in Lutz, FL. Licensed technicians serving this growing suburb north of Tampa. Call (813) 291-6146 for fast service.`,
    heroSubhead: `Expert heating and cooling services for Lutz's rapidly growing residential and commercial communities north of Tampa.`,
    heroPhotoId: '4078319',
    introParagraphs: [
      `Lutz is one of the Tampa Bay area's fastest-growing communities, attracting new residents drawn by its combination of suburban convenience, quality schools, and proximity to Tampa's employment centers. As Lutz continues to grow, so does the demand for reliable HVAC services. Florida's hot and humid climate makes air conditioning not just a comfort, but a daily necessity — and Lutz residents know that their cooling systems need to perform flawlessly through long, sweltering summers.`,
      `North East Heating And Cooling serves Lutz homeowners and businesses with comprehensive HVAC repair, installation, and maintenance services. Whether you're in an established neighborhood or a newer development, our licensed technicians bring the expertise and equipment needed to keep your home or business at the perfect temperature year-round.`,
    ],
    faqs: [
      { q: `Do you install ductless mini-splits in Lutz?`, a: `Yes. We install single-zone and multi-zone ductless mini-splits throughout Lutz — perfect for additions, garages, sunrooms, or older homes without ductwork. We work with premium brands including Mitsubishi, Daikin, LG, and Fujitsu, and provide free in-home assessments to determine the right system size.` },
      { q: `How often should I have my AC maintained in Lutz?`, a: `Twice a year — once in spring (March–April) before peak cooling, and once in fall (October–November). Tampa Bay's climate puts significantly more wear on AC systems than northern climates, so twice-yearly service is the standard for keeping equipment running efficiently and avoiding mid-summer breakdowns. Our maintenance plans for Lutz start at $19/mo.` },
      { q: `Do you offer maintenance plans in Lutz?`, a: `Yes. Our maintenance plans for Lutz customers include twice-yearly tune-ups, a 20-point inspection at every visit, priority scheduling during peak seasons, a 15% discount on any repairs, and no diagnostic fees. Plans start at $19/mo with no long-term contract — cancel any time.` },
      { q: `Do you offer 24/7 emergency HVAC service in Lutz?`, a: `Yes. We provide 24/7 emergency AC repair throughout Lutz — Florida's heat makes a broken AC a health concern within hours, especially for elderly residents, young children, and pets. When you call our emergency line, a live technician answers and we dispatch the nearest available crew.` },
      { q: `How quickly can you get to Lutz for an AC repair?`, a: `For most Lutz service calls we offer same-day or next-day appointments. For emergency breakdowns we dispatch the nearest technician — typically within 1–2 hours depending on traffic and current service volume. Our service vans are stocked with the most common repair parts so the majority of repairs are resolved on the first visit.` },
      { q: `Do you charge a service fee for AC repair calls in Lutz?`, a: `We charge a standard diagnostic fee that covers the technician's travel and full system inspection. The diagnostic fee is waived if you proceed with the repair, and members of our maintenance plan don't pay it at all. Every repair quote is provided in writing before any work begins — no surprise charges.` },
    ],
  },
  'land-o-lakes-fl': {
    slug: 'land-o-lakes-fl',
    display: "Land O' Lakes",
    county: 'Pasco County',
    lat: 28.2189,
    lng: -82.4592,
    coastal: false,
    tier: 'mid',
    metaDescription: `Professional HVAC repair, AC installation & maintenance in Land O Lakes, FL. Licensed technicians serving this rural-suburban community in Pasco County. Call (813) 291-6146 for fast service.`,
    heroSubhead: `Dependable heating and cooling solutions for Land O Lakes' rural-suburban neighborhoods and newer residential developments in Pasco County.`,
    heroPhotoId: '3855962',
    introParagraphs: [
      `Land O Lakes is a unique community in Pasco County that blends rural character with suburban convenience. Known for its natural scenery, numerous lakes, and spacious properties, Land O Lakes has grown steadily as Tampa Bay area residents seek more space while staying connected to the region's employment and amenities. Whether you live in a sprawling rural property or one of the area's newer residential developments, reliable HVAC service is essential for comfort in Florida's demanding climate.`,
      `North East Heating And Cooling serves Land O Lakes homeowners and businesses with comprehensive HVAC services. Our technicians are experienced with the full range of property types found in the area — from large homes with complex multi-zone systems to newer construction in planned developments. We deliver professional, prompt service with the honest, straightforward approach that Land O Lakes residents appreciate.`,
    ],
    faqs: [
      { q: `Do you offer maintenance plans in Land O' Lakes?`, a: `Yes. Our maintenance plans for Land O' Lakes customers include twice-yearly tune-ups, a 20-point inspection at every visit, priority scheduling during peak seasons, a 15% discount on any repairs, and no diagnostic fees. Plans start at $19/mo with no long-term contract — cancel any time.` },
      { q: `Do you offer 24/7 emergency HVAC service in Land O' Lakes?`, a: `Yes. We provide 24/7 emergency AC repair throughout Land O' Lakes — Florida's heat makes a broken AC a health concern within hours, especially for elderly residents, young children, and pets. When you call our emergency line, a live technician answers and we dispatch the nearest available crew.` },
      { q: `How quickly can you get to Land O' Lakes for an AC repair?`, a: `For most Land O' Lakes service calls we offer same-day or next-day appointments. For emergency breakdowns we dispatch the nearest technician — typically within 1–2 hours depending on traffic and current service volume. Our service vans are stocked with the most common repair parts so the majority of repairs are resolved on the first visit.` },
      { q: `Do you charge a service fee for AC repair calls in Land O' Lakes?`, a: `We charge a standard diagnostic fee that covers the technician's travel and full system inspection. The diagnostic fee is waived if you proceed with the repair, and members of our maintenance plan don't pay it at all. Every repair quote is provided in writing before any work begins — no surprise charges.` },
      { q: `What is the average cost of AC repair in Land O' Lakes?`, a: `Most Land O' Lakes AC repairs fall in the $150–$600 range. Common fixes like capacitor replacement run $150–$300, while bigger jobs like compressor replacement can reach $1,000–$1,800. We always quote in writing upfront, and on aging systems we'll quote both the repair cost and a replacement option side-by-side so you can choose with full information.` },
      { q: `What areas of Land O' Lakes do you serve?`, a: `We serve all of Land O' Lakes and the surrounding Pasco County area. Our techs cover every neighborhood in the city, from established residential areas to newer developments. We typically arrive within our standard service window regardless of where you are in Land O' Lakes.` },
    ],
  },
  'odessa-fl': {
    slug: 'odessa-fl',
    display: "Odessa",
    county: 'Pasco County',
    lat: 28.1872,
    lng: -82.5912,
    coastal: false,
    tier: 'mid',
    metaDescription: `Professional HVAC repair, AC installation & maintenance in Odessa, FL. Licensed technicians serving upscale residential communities west of Tampa. Call (813) 291-6146 for fast service.`,
    heroSubhead: `Premium HVAC repair, installation, and maintenance for Odessa's upscale residential communities and businesses west of Tampa.`,
    heroPhotoId: '7983215',
    introParagraphs: [
      `Odessa is one of Tampa Bay's most desirable residential communities, known for its spacious homes, upscale neighborhoods, and scenic lakes. Located just west of Tampa along the Hillsborough-Pasco county border, Odessa attracts discerning homeowners who expect the best — including when it comes to HVAC service. With Florida's demanding climate, a properly sized and well-maintained cooling system is essential to protecting both your family's comfort and your home's value.`,
      `North East Heating And Cooling provides the professional, high-quality HVAC service that Odessa residents expect. Our licensed technicians are experienced in servicing larger and more complex residential HVAC systems common in upscale homes. We offer thorough assessments, premium equipment options, and meticulous installations — all backed by our commitment to customer satisfaction.`,
    ],
    faqs: [
      { q: `How quickly can you get to Odessa for an AC repair?`, a: `For most Odessa service calls we offer same-day or next-day appointments. For emergency breakdowns we dispatch the nearest technician — typically within 1–2 hours depending on traffic and current service volume. Our service vans are stocked with the most common repair parts so the majority of repairs are resolved on the first visit.` },
      { q: `Do you charge a service fee for AC repair calls in Odessa?`, a: `We charge a standard diagnostic fee that covers the technician's travel and full system inspection. The diagnostic fee is waived if you proceed with the repair, and members of our maintenance plan don't pay it at all. Every repair quote is provided in writing before any work begins — no surprise charges.` },
      { q: `What is the average cost of AC repair in Odessa?`, a: `Most Odessa AC repairs fall in the $150–$600 range. Common fixes like capacitor replacement run $150–$300, while bigger jobs like compressor replacement can reach $1,000–$1,800. We always quote in writing upfront, and on aging systems we'll quote both the repair cost and a replacement option side-by-side so you can choose with full information.` },
      { q: `What areas of Odessa do you serve?`, a: `We serve all of Odessa and the surrounding Pasco County area. Our techs cover every neighborhood in the city, from established residential areas to newer developments. We typically arrive within our standard service window regardless of where you are in Odessa.` },
      { q: `Do you service mobile homes in Odessa?`, a: `Yes — we service all types of residential properties in Odessa, including mobile homes, manufactured homes, and modular homes. Mobile home HVAC systems often have unique configurations (like under-floor ductwork or roof-mounted package units) that require specific expertise. Our technicians are trained on these systems.` },
      { q: `Do you handle both residential and commercial work in Odessa?`, a: `Yes. We service residential homes, small commercial buildings, restaurants, retail locations, and offices throughout Odessa. Commercial clients typically receive priority dispatch since downtime affects business operations. We work on rooftop units, split systems, and packaged units of all sizes.` },
    ],
  },
  'new-port-richey-fl': {
    slug: 'new-port-richey-fl',
    display: "New Port Richey",
    county: 'Pasco County',
    lat: 28.244,
    lng: -82.7193,
    coastal: true,
    tier: 'mid',
    metaDescription: `Professional HVAC repair, AC installation & maintenance in New Port Richey, FL. Licensed technicians serving this older coastal community in Pasco County. Call (813) 291-6146 for fast service.`,
    heroSubhead: `Trusted heating and cooling services for New Port Richey's established coastal neighborhoods and diverse mix of residential and commercial properties.`,
    heroPhotoId: '3875141',
    introParagraphs: [
      `New Port Richey is one of Pasco County's oldest and most established communities, with a rich history, a vibrant downtown district, and a mix of long-time residents and newer arrivals. Situated along the Gulf Coast just north of the Pinellas County line, New Port Richey enjoys the natural beauty of the Pithlachascotee River and easy access to coastal waterways. Its coastal location and warm, humid climate make reliable air conditioning essential for comfortable living year-round.`,
      `North East Heating And Cooling provides comprehensive HVAC services throughout New Port Richey, serving homeowners and businesses across the city's diverse neighborhoods. Our licensed technicians are experienced with the older housing stock and systems commonly found in New Port Richey, and we bring the same level of professionalism and honest service to every job regardless of the age or complexity of your property.`,
    ],
    faqs: [
      { q: `How do you protect HVAC equipment from New Port Richey's coastal environment?`, a: `For coastal New Port Richey installations we recommend equipment with corrosion-resistant coatings on the outdoor condenser, more frequent coil cleaning to remove salt deposits, and protective covers for unused months. Ground-level installations should be elevated to protect against tropical storm surge. We help homeowners choose equipment specifically rated for coastal climates.` },
      { q: `Do you offer 24/7 emergency HVAC service in New Port Richey?`, a: `Yes. We provide 24/7 emergency AC repair throughout New Port Richey — Florida's heat makes a broken AC a health concern within hours, especially for elderly residents, young children, and pets. When you call our emergency line, a live technician answers and we dispatch the nearest available crew.` },
      { q: `How quickly can you get to New Port Richey for an AC repair?`, a: `For most New Port Richey service calls we offer same-day or next-day appointments. For emergency breakdowns we dispatch the nearest technician — typically within 1–2 hours depending on traffic and current service volume. Our service vans are stocked with the most common repair parts so the majority of repairs are resolved on the first visit.` },
      { q: `Do you charge a service fee for AC repair calls in New Port Richey?`, a: `We charge a standard diagnostic fee that covers the technician's travel and full system inspection. The diagnostic fee is waived if you proceed with the repair, and members of our maintenance plan don't pay it at all. Every repair quote is provided in writing before any work begins — no surprise charges.` },
      { q: `What is the average cost of AC repair in New Port Richey?`, a: `Most New Port Richey AC repairs fall in the $150–$600 range. Common fixes like capacitor replacement run $150–$300, while bigger jobs like compressor replacement can reach $1,000–$1,800. We always quote in writing upfront, and on aging systems we'll quote both the repair cost and a replacement option side-by-side so you can choose with full information.` },
      { q: `What areas of New Port Richey do you serve?`, a: `We serve all of New Port Richey and the surrounding Pasco County area. Our techs cover every neighborhood in the city, from established residential areas to newer developments. We typically arrive within our standard service window regardless of where you are in New Port Richey.` },
    ],
  },
  'apollo-beach-fl': {
    slug: 'apollo-beach-fl',
    display: "Apollo Beach",
    county: 'Hillsborough County',
    lat: 27.7711,
    lng: -82.4023,
    coastal: true,
    tier: 'mid',
    metaDescription: `Expert HVAC repair, AC installation, heating services, and air duct repair in Apollo Beach, FL. North East Heating And Cooling — call (813) 291-6146 for coastal HVAC specialists.`,
    heroSubhead: `Coastal HVAC specialists serving Apollo Beach homeowners and waterfront properties. Expert heating, cooling, and air quality service built for Tampa Bay's unique marine environment.`,
    heroPhotoId: '5825527',
    introParagraphs: [
      `Apollo Beach is one of Tampa Bay's most desirable waterfront communities, situated along the eastern shore of Tampa Bay in southern Hillsborough County. Known for its navigable canals, direct bay access, and stunning water views, Apollo Beach attracts residents who appreciate the Florida waterfront lifestyle — and who understand that coastal living comes with some unique maintenance considerations, particularly when it comes to HVAC equipment.`,
      `Homes in Apollo Beach are exposed to the salt air carried in from Tampa Bay on the prevailing sea breeze. This salt-laden air is highly corrosive to metal HVAC components, particularly condenser coils, electrical contacts, and refrigerant line connections. Systems in Apollo Beach and other waterfront communities can show significant corrosion damage in just a few years if they are not specifically designed for coastal environments or protected with appropriate coatings and regular maintenance. North East Heating And Cooling's technicians are experienced in servicing HVAC systems in Apollo Beach's marine environment and can recommend the right equipment choices and maintenance practices to protect your investment.`,
    ],
    faqs: [
      { q: `How quickly can you get to Apollo Beach for an AC repair?`, a: `For most Apollo Beach service calls we offer same-day or next-day appointments. For emergency breakdowns we dispatch the nearest technician — typically within 1–2 hours depending on traffic and current service volume. Our service vans are stocked with the most common repair parts so the majority of repairs are resolved on the first visit.` },
      { q: `Do you charge a service fee for AC repair calls in Apollo Beach?`, a: `We charge a standard diagnostic fee that covers the technician's travel and full system inspection. The diagnostic fee is waived if you proceed with the repair, and members of our maintenance plan don't pay it at all. Every repair quote is provided in writing before any work begins — no surprise charges.` },
      { q: `What is the average cost of AC repair in Apollo Beach?`, a: `Most Apollo Beach AC repairs fall in the $150–$600 range. Common fixes like capacitor replacement run $150–$300, while bigger jobs like compressor replacement can reach $1,000–$1,800. We always quote in writing upfront, and on aging systems we'll quote both the repair cost and a replacement option side-by-side so you can choose with full information.` },
      { q: `What areas of Apollo Beach do you serve?`, a: `We serve all of Apollo Beach and the surrounding Hillsborough County area. Our techs cover every neighborhood in the city, from established residential areas to newer developments. We typically arrive within our standard service window regardless of where you are in Apollo Beach.` },
      { q: `Do you service mobile homes in Apollo Beach?`, a: `Yes — we service all types of residential properties in Apollo Beach, including mobile homes, manufactured homes, and modular homes. Mobile home HVAC systems often have unique configurations (like under-floor ductwork or roof-mounted package units) that require specific expertise. Our technicians are trained on these systems.` },
      { q: `Do you handle both residential and commercial work in Apollo Beach?`, a: `Yes. We service residential homes, small commercial buildings, restaurants, retail locations, and offices throughout Apollo Beach. Commercial clients typically receive priority dispatch since downtime affects business operations. We work on rooftop units, split systems, and packaged units of all sizes.` },
    ],
  },
  'sun-city-center-fl': {
    slug: 'sun-city-center-fl',
    display: "Sun City Center",
    county: 'Hillsborough County',
    lat: 27.7152,
    lng: -82.3543,
    coastal: false,
    tier: 'mid',
    metaDescription: `Professional HVAC repair, AC installation & maintenance in Sun City Center, FL. Licensed technicians serving retirement communities. Call (813) 291-6146 for fast service.`,
    heroSubhead: `Trusted heating and cooling solutions for Sun City Center's retirement communities and HOA neighborhoods.`,
    heroPhotoId: '7534294',
    introParagraphs: [
      `Sun City Center is one of Florida's most celebrated active adult retirement communities, home to thousands of residents who depend on reliable HVAC systems year-round. With the Florida heat bearing down from spring through fall and mild but unpredictable winters, keeping your heating and cooling system in peak condition is not a luxury — it's a necessity. North East Heating And Cooling provides comprehensive HVAC services tailored to the unique demands of Sun City Center's retirement community lifestyle.`,
      `Many homes in Sun City Center were built decades ago, and older HVAC equipment can struggle to keep up with modern efficiency standards. Whether you live in a standalone villa, a single-family home within an HOA community, or a condo, our licensed technicians understand the specific requirements of these properties. We deliver fast, respectful service with transparent pricing — because your comfort and peace of mind matter.`,
    ],
    faqs: [
      { q: `What HVAC brands do you service in Sun City Center?`, a: `We service every major HVAC brand: Carrier, Trane, Lennox, Rheem, Goodman, York, American Standard, Bryant, Daikin, Mitsubishi, and others. Our service vans carry parts for the most common brands and we can source specialty parts within 24–48 hours when needed. We work on systems from any installer, including ones we didn't install.` },
      { q: `Do you install heat pumps in Sun City Center?`, a: `Yes. Heat pumps are an excellent choice for Sun City Center given Florida's mild winters — they handle both cooling and heating efficiently year-round. We install variable-speed inverter heat pumps, traditional split heat pumps, and packaged units. Many qualifying systems are eligible for federal tax credits up to $2,000.` },
      { q: `Do you install ductless mini-splits in Sun City Center?`, a: `Yes. We install single-zone and multi-zone ductless mini-splits throughout Sun City Center — perfect for additions, garages, sunrooms, or older homes without ductwork. We work with premium brands including Mitsubishi, Daikin, LG, and Fujitsu, and provide free in-home assessments to determine the right system size.` },
      { q: `How often should I have my AC maintained in Sun City Center?`, a: `Twice a year — once in spring (March–April) before peak cooling, and once in fall (October–November). Tampa Bay's climate puts significantly more wear on AC systems than northern climates, so twice-yearly service is the standard for keeping equipment running efficiently and avoiding mid-summer breakdowns. Our maintenance plans for Sun City Center start at $19/mo.` },
      { q: `Do you offer maintenance plans in Sun City Center?`, a: `Yes. Our maintenance plans for Sun City Center customers include twice-yearly tune-ups, a 20-point inspection at every visit, priority scheduling during peak seasons, a 15% discount on any repairs, and no diagnostic fees. Plans start at $19/mo with no long-term contract — cancel any time.` },
      { q: `Do you offer 24/7 emergency HVAC service in Sun City Center?`, a: `Yes. We provide 24/7 emergency AC repair throughout Sun City Center — Florida's heat makes a broken AC a health concern within hours, especially for elderly residents, young children, and pets. When you call our emergency line, a live technician answers and we dispatch the nearest available crew.` },
    ],
  },
  'ruskin-fl': {
    slug: 'ruskin-fl',
    display: "Ruskin",
    county: 'Hillsborough County',
    lat: 27.7203,
    lng: -82.4337,
    coastal: true,
    tier: 'mid',
    metaDescription: `Full-service HVAC repair, AC installation, heating services, and air duct repair in Ruskin, FL. North East Heating And Cooling — call (813) 291-6146 for expert south Hillsborough HVAC.`,
    heroSubhead: `Professional heating and cooling services for Ruskin's growing residential community and local businesses. Fast response, transparent pricing, and HVAC expertise you can count on.`,
    heroPhotoId: '7577378',
    introParagraphs: [
      `Ruskin is a growing unincorporated community in the southernmost part of Hillsborough County, bordered by Tampa Bay to the west and the Little Manatee River to the south. With a population approaching 25,000 residents and significant new residential development underway, Ruskin is one of the Tampa Bay region's emerging communities, attracting families and retirees who appreciate its mix of agricultural character, waterfront access, and proximity to major employers throughout south Hillsborough County.`,
      `Ruskin's southern location near Tampa Bay means the community experiences the full subtropical heat of Florida's summer, along with high humidity levels that persist throughout much of the year. The combination of heat, humidity, and Ruskin's proximity to the bay creates demanding conditions for HVAC equipment. Systems here must work hard to maintain comfortable indoor temperatures and humidity levels, and regular maintenance is essential to prevent the premature failures that Florida's climate accelerates.`,
    ],
    faqs: [
      { q: `Do you service mobile homes in Ruskin?`, a: `Yes — we service all types of residential properties in Ruskin, including mobile homes, manufactured homes, and modular homes. Mobile home HVAC systems often have unique configurations (like under-floor ductwork or roof-mounted package units) that require specific expertise. Our technicians are trained on these systems.` },
      { q: `Do you handle both residential and commercial work in Ruskin?`, a: `Yes. We service residential homes, small commercial buildings, restaurants, retail locations, and offices throughout Ruskin. Commercial clients typically receive priority dispatch since downtime affects business operations. We work on rooftop units, split systems, and packaged units of all sizes.` },
      { q: `What HVAC brands do you service in Ruskin?`, a: `We service every major HVAC brand: Carrier, Trane, Lennox, Rheem, Goodman, York, American Standard, Bryant, Daikin, Mitsubishi, and others. Our service vans carry parts for the most common brands and we can source specialty parts within 24–48 hours when needed. We work on systems from any installer, including ones we didn't install.` },
      { q: `Do you install heat pumps in Ruskin?`, a: `Yes. Heat pumps are an excellent choice for Ruskin given Florida's mild winters — they handle both cooling and heating efficiently year-round. We install variable-speed inverter heat pumps, traditional split heat pumps, and packaged units. Many qualifying systems are eligible for federal tax credits up to $2,000.` },
      { q: `Do you install ductless mini-splits in Ruskin?`, a: `Yes. We install single-zone and multi-zone ductless mini-splits throughout Ruskin — perfect for additions, garages, sunrooms, or older homes without ductwork. We work with premium brands including Mitsubishi, Daikin, LG, and Fujitsu, and provide free in-home assessments to determine the right system size.` },
      { q: `How often should I have my AC maintained in Ruskin?`, a: `Twice a year — once in spring (March–April) before peak cooling, and once in fall (October–November). Tampa Bay's climate puts significantly more wear on AC systems than northern climates, so twice-yearly service is the standard for keeping equipment running efficiently and avoiding mid-summer breakdowns. Our maintenance plans for Ruskin start at $19/mo.` },
    ],
  },
  'gibsonton-fl': {
    slug: 'gibsonton-fl',
    display: "Gibsonton",
    county: 'Hillsborough County',
    lat: 27.8542,
    lng: -82.3793,
    coastal: true,
    tier: 'mid',
    metaDescription: `Affordable HVAC repair, AC installation, heating services, and air duct repair in Gibsonton, FL. North East Heating And Cooling — call (813) 291-6146 for fast, local service.`,
    heroSubhead: `Affordable, reliable heating and cooling services for Gibsonton homes and businesses. Licensed HVAC technicians serving south Hillsborough County with same-day availability.`,
    heroPhotoId: '8961065',
    introParagraphs: [
      `Gibsonton is a unique and close-knit unincorporated community in southern Hillsborough County, situated between Riverview and Apollo Beach along the eastern shore of Tampa Bay. With a population of approximately 14,000 residents, Gibsonton has a tight community feel and a distinctive character that sets it apart from the larger suburban developments surrounding it. The community is conveniently located near US-41, providing easy access to Tampa, Brandon, and the growing communities to the south.`,
      `Gibsonton's location near Tampa Bay means residents experience some of the same coastal humidity challenges as neighboring Apollo Beach and Ruskin. High humidity levels throughout the year place significant demands on air conditioning systems, which must not only cool the air but also remove substantial amounts of moisture to maintain comfortable indoor conditions. A properly sized, well-maintained HVAC system is essential for healthy, comfortable living in Gibsonton's warm, humid climate.`,
    ],
    faqs: [
      { q: `What HVAC brands do you service in Gibsonton?`, a: `We service every major HVAC brand: Carrier, Trane, Lennox, Rheem, Goodman, York, American Standard, Bryant, Daikin, Mitsubishi, and others. Our service vans carry parts for the most common brands and we can source specialty parts within 24–48 hours when needed. We work on systems from any installer, including ones we didn't install.` },
      { q: `Do you install heat pumps in Gibsonton?`, a: `Yes. Heat pumps are an excellent choice for Gibsonton given Florida's mild winters — they handle both cooling and heating efficiently year-round. We install variable-speed inverter heat pumps, traditional split heat pumps, and packaged units. Many qualifying systems are eligible for federal tax credits up to $2,000.` },
      { q: `Do you install ductless mini-splits in Gibsonton?`, a: `Yes. We install single-zone and multi-zone ductless mini-splits throughout Gibsonton — perfect for additions, garages, sunrooms, or older homes without ductwork. We work with premium brands including Mitsubishi, Daikin, LG, and Fujitsu, and provide free in-home assessments to determine the right system size.` },
      { q: `How often should I have my AC maintained in Gibsonton?`, a: `Twice a year — once in spring (March–April) before peak cooling, and once in fall (October–November). Tampa Bay's climate puts significantly more wear on AC systems than northern climates, so twice-yearly service is the standard for keeping equipment running efficiently and avoiding mid-summer breakdowns. Our maintenance plans for Gibsonton start at $19/mo.` },
      { q: `Do you offer maintenance plans in Gibsonton?`, a: `Yes. Our maintenance plans for Gibsonton customers include twice-yearly tune-ups, a 20-point inspection at every visit, priority scheduling during peak seasons, a 15% discount on any repairs, and no diagnostic fees. Plans start at $19/mo with no long-term contract — cancel any time.` },
      { q: `Does the salt air in Gibsonton affect my AC system?`, a: `Yes — homes in Gibsonton near the water are exposed to salt-laden humidity that accelerates corrosion of aluminum coil fins, copper refrigerant lines, and outdoor electrical contacts. Coastal homes typically see AC lifespan reduced by 2–4 years compared to inland homes. We recommend coastal-rated equipment with corrosion-resistant coatings for waterfront installations, plus more aggressive maintenance schedules.` },
    ],
  },
  'valrico-fl': {
    slug: 'valrico-fl',
    display: "Valrico",
    county: 'Hillsborough County',
    lat: 27.9389,
    lng: -82.2362,
    coastal: false,
    tier: 'mid',
    metaDescription: `Reliable HVAC repair, AC installation, heating services, and air duct repair in Valrico, FL. North East Heating And Cooling — call (813) 291-6146 for expert service.`,
    heroSubhead: `Dependable heating and cooling services for Valrico homes and businesses. Local knowledge, honest pricing, and fast response throughout eastern Hillsborough County.`,
    heroPhotoId: '4078319',
    introParagraphs: [
      `Valrico is a quiet, unincorporated community in eastern Hillsborough County that offers residents a suburban lifestyle with convenient access to both Brandon and Tampa. Home to approximately 38,000 residents, Valrico is characterized by established single-family neighborhoods, larger lots, good schools, and a strong sense of community. Neighborhoods like Buckhorn and Canterbury Lakes have been established for decades, while newer developments continue to fill in the community's remaining undeveloped land.`,
      `Valrico's eastern Hillsborough County location places it slightly inland from the coast, meaning it experiences some of the highest summer temperatures in the Tampa Bay region without the slight moderating influence of Tampa Bay or the Gulf. Afternoon heat indexes regularly reach 105–110°F during peak summer, making a reliable, efficiently running air conditioning system a genuine necessity for Valrico families.`,
    ],
    faqs: [
      { q: `How quickly can you get to Valrico for an AC repair?`, a: `For most Valrico service calls we offer same-day or next-day appointments. For emergency breakdowns we dispatch the nearest technician — typically within 1–2 hours depending on traffic and current service volume. Our service vans are stocked with the most common repair parts so the majority of repairs are resolved on the first visit.` },
      { q: `Do you charge a service fee for AC repair calls in Valrico?`, a: `We charge a standard diagnostic fee that covers the technician's travel and full system inspection. The diagnostic fee is waived if you proceed with the repair, and members of our maintenance plan don't pay it at all. Every repair quote is provided in writing before any work begins — no surprise charges.` },
      { q: `What is the average cost of AC repair in Valrico?`, a: `Most Valrico AC repairs fall in the $150–$600 range. Common fixes like capacitor replacement run $150–$300, while bigger jobs like compressor replacement can reach $1,000–$1,800. We always quote in writing upfront, and on aging systems we'll quote both the repair cost and a replacement option side-by-side so you can choose with full information.` },
      { q: `What areas of Valrico do you serve?`, a: `We serve all of Valrico and the surrounding Hillsborough County area. Our techs cover every neighborhood in the city, from established residential areas to newer developments. We typically arrive within our standard service window regardless of where you are in Valrico.` },
      { q: `Do you service mobile homes in Valrico?`, a: `Yes — we service all types of residential properties in Valrico, including mobile homes, manufactured homes, and modular homes. Mobile home HVAC systems often have unique configurations (like under-floor ductwork or roof-mounted package units) that require specific expertise. Our technicians are trained on these systems.` },
      { q: `Do you handle both residential and commercial work in Valrico?`, a: `Yes. We service residential homes, small commercial buildings, restaurants, retail locations, and offices throughout Valrico. Commercial clients typically receive priority dispatch since downtime affects business operations. We work on rooftop units, split systems, and packaged units of all sizes.` },
    ],
  },
  'plant-city-fl': {
    slug: 'plant-city-fl',
    display: "Plant City",
    county: 'Hillsborough County',
    lat: 28.0186,
    lng: -82.1148,
    coastal: false,
    tier: 'mid',
    metaDescription: `Professional HVAC repair, AC installation, heating services, and air duct repair in Plant City, FL. North East Heating And Cooling — call (813) 291-6146 for fast, reliable service.`,
    heroSubhead: `Reliable heating and cooling services for Plant City homes and businesses. Local HVAC experts serving Hillsborough County's eastern communities with fast response and honest pricing.`,
    heroPhotoId: '3855962',
    introParagraphs: [
      `Plant City is a proud, independent city in eastern Hillsborough County with a population of approximately 40,000 residents. Known as the "Winter Strawberry Capital of the World," Plant City celebrates its agricultural heritage each year at the Florida Strawberry Festival, one of Florida's largest and most beloved annual events. Beyond its farming roots, Plant City has evolved into a thriving small city with a historic downtown district, growing residential neighborhoods, and an expanding commercial and industrial base along the Interstate 4 corridor.`,
      `Plant City's location in Hillsborough County's interior means it experiences some of the warmest summer temperatures in the Tampa Bay area, with afternoon highs routinely reaching the mid-to-upper 90s from May through September. Combined with high humidity, summer heat in Plant City can be intense, and the city's many older homes — some dating back to the early 20th century in the historic downtown area — present unique HVAC challenges around ductwork, insulation, and equipment placement.`,
    ],
    faqs: [
      { q: `What is the average cost of AC repair in Plant City?`, a: `Most Plant City AC repairs fall in the $150–$600 range. Common fixes like capacitor replacement run $150–$300, while bigger jobs like compressor replacement can reach $1,000–$1,800. We always quote in writing upfront, and on aging systems we'll quote both the repair cost and a replacement option side-by-side so you can choose with full information.` },
      { q: `What areas of Plant City do you serve?`, a: `We serve all of Plant City and the surrounding Hillsborough County area. Our techs cover every neighborhood in the city, from established residential areas to newer developments. We typically arrive within our standard service window regardless of where you are in Plant City.` },
      { q: `Do you service mobile homes in Plant City?`, a: `Yes — we service all types of residential properties in Plant City, including mobile homes, manufactured homes, and modular homes. Mobile home HVAC systems often have unique configurations (like under-floor ductwork or roof-mounted package units) that require specific expertise. Our technicians are trained on these systems.` },
      { q: `Do you handle both residential and commercial work in Plant City?`, a: `Yes. We service residential homes, small commercial buildings, restaurants, retail locations, and offices throughout Plant City. Commercial clients typically receive priority dispatch since downtime affects business operations. We work on rooftop units, split systems, and packaged units of all sizes.` },
      { q: `What HVAC brands do you service in Plant City?`, a: `We service every major HVAC brand: Carrier, Trane, Lennox, Rheem, Goodman, York, American Standard, Bryant, Daikin, Mitsubishi, and others. Our service vans carry parts for the most common brands and we can source specialty parts within 24–48 hours when needed. We work on systems from any installer, including ones we didn't install.` },
      { q: `Do you install heat pumps in Plant City?`, a: `Yes. Heat pumps are an excellent choice for Plant City given Florida's mild winters — they handle both cooling and heating efficiently year-round. We install variable-speed inverter heat pumps, traditional split heat pumps, and packaged units. Many qualifying systems are eligible for federal tax credits up to $2,000.` },
    ],
  },
}

export const CITY_SLUGS = Object.keys(CITIES)
